//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect_ABD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activitate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Activitate()
        {
            this.CopilActivitates = new HashSet<CopilActivitate>();
        }
    
        public int ActivitateID { get; set; }
        public string Nume { get; set; }
        public string Descriere { get; set; }
        public System.DateTime Data { get; set; }
        public System.TimeSpan Ora { get; set; }
        public int Durata { get; set; }
        public int EducatorID { get; set; }
    
        public virtual Educator Educator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CopilActivitate> CopilActivitates { get; set; }
    }
}
