//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect_ABD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CopilActivitate
    {
        public int CopilID { get; set; }
        public int ActivitateID { get; set; }
        public bool Prezenta { get; set; }
        public string Observatii { get; set; }
    
        public virtual Activitate Activitate { get; set; }
        public virtual Copil Copil { get; set; }
    }
}
