//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect_ABD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TabaraDeVaraEntities : DbContext
    {
        public TabaraDeVaraEntities()
            : base("name=TabaraDeVaraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activitate> Activitates { get; set; }
        public virtual DbSet<Copil> Copils { get; set; }
        public virtual DbSet<CopilActivitate> CopilActivitates { get; set; }
        public virtual DbSet<CopilParinte> CopilParintes { get; set; }
        public virtual DbSet<Educator> Educators { get; set; }
        public virtual DbSet<Parinte> Parintes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
