//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect_ABD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TabaraDeVaraEntities3 : DbContext
    {
        public TabaraDeVaraEntities3()
            : base("name=TabaraDeVaraEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activitate> Activitate { get; set; }
        public virtual DbSet<Copil> Copil { get; set; }
        public virtual DbSet<CopilActivitate> CopilActivitate { get; set; }
        public virtual DbSet<Educator> Educator { get; set; }
        public virtual DbSet<Parinte> Parinte { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
